apiVersion: apps/v1
kind: Deployment
metadata:
  name: seksctl
  labels:
    app: spring

spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring
  
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
        - name: spring-container
          image: 670154208195.dkr.ecr.us-west-1.amazonaws.com/spring-vas:latest
          ports:
            - containerPort: 8080